gisce/enerdata

enerdata/profiles/__init__.py
enerdata/profiles/profile.py
setup.py

Use [backport_collections](https://pypi.python.org/pypi/backport_collections) if python version is lower than `2.7`

Add py26 compat

---

enerdata/metering/measure.py
enerdata/profiles/profile.py
spec/metering/measure_spec.py
spec/profiles/profile_spec.py

- New method to get intervals of measures.
- Fix profiling when profiling more then one measure in the same time.

More than one measure profiling

---

enerdata/profiles/profile.py
spec/profiles/profile_spec.py

Tets if the period exists on measures when profiling

FIX Better period checking on profiling

---

enerdata/profiles/profile.py
spec/profiles/gaps_spec.py

Test adjust per period

---

enerdata/contracts/tariff.py
spec/contracts/tariff_spec.py

Tariff.cof attribute defined for all Tariffs

---

setup.py

Bump to v0.9.2

---

enerdata/contracts/tariff.py
spec/contracts/tariff_spec.py

Added functions to get the min and max powers of a tariff (basicly to keep the object encapsulation)
**TO BE MERGED**

New: Get min max powers

---

.travis.yml

Add autodeploy when create a new release

Add travis with autodeploy

---

enerdata/contracts/tariff.py
spec/contracts/tariff_spec.py

FIX Get tariff by code for 3.1A LB tariffs

FIX `get_tariff_by_code` for 3.1A LB

---

spec/contracts/tariff_spec.py

FIX Localized datetime in tests

---

README.rst

Add some considerations about how to pass dates to Enerdata

Add considerations section

---

setup.py

Missing data xlsx file on pip generation

FIX no data in pip file

---

enerdata/profiles/profile.py
spec/profiles/profile_spec.py

- It should be verified that the RE curves do not contain measurements greater than zero during night periods.
- A function has been implemented to check whether there are energy measurements greater than zero in periods with zero generation coefficient (nighttime).
Closes #125

Assert no energy in periods with zero generation coefficient

---

setup.py

Set setup description

---

enerdata/contracts/tariff.py
spec/contracts/tariff_spec.py

New 6x tariffs

---

enerdata/profiles/profile.py
spec/profiles/profile_spec.py

According to **Real Decreto 413/2014**:
[BOE-A-2014-6123 - ANEXO IV - Resto de tecnologías - perfiles horarios para las instalaciones que no cuenten con medida horaria](https://www.boe.es/buscar/act.php?id=BOE-A-2014-6123)
Profile curve with the same flat `0.85` cof.

Profile with flat coff

---

enerdata/profiles/profile.py

If cannot verify www.ree.es's certificate, ignored this on HTTPS Connection

Ignore certificate on download PERFF files

---

enerdata/contracts/tariff.py
spec/contracts/tariff_spec.py

FIX potencia máxima para tarifas 6.x

FIX potencia máxima para tarifas 6.x

---

enerdata/contracts/tariff.py
enerdata/profiles/profile.py
spec/contracts/tariff_spec.py

- Apply curve losses on `6.XTD` tariffs

Apply losses on 6.XTD

---

.github/pull_request_template.md
.github/workflows/python2.7-app.yml
.github/workflows/python3.10-app.yml
.github/workflows/python3.11-app.yml
.github/workflows/python3.6-app.yml
.github/workflows/python3.7-app.yml
.github/workflows/python3.8-app.yml
.github/workflows/python3.9-app.yml
README.rst
requirements.txt

- Se han añadido tests para `Python 3.6`, `Python 3.8`, `Python 3.9`, `Python 3.10` y `Python 3.11`.
- Se ha actualizado el fichero `README`.

Compatibilidad hasta Python3.11
