gisce/enerdata

- enerdata/profiles/__init__.py
- spec/profiles/dragger_spec.py
If dragger receives 0.5 and 0s, it returns an oscillation between 1 and -1 dragging -0.5 and 0.5.
This pull request fixes it and adds a spec to specify that it must return 1 and 0s and dragging -0.5.
> Fix dragger oscillation

- enerdata/profiles/profile.py
- setup.py
- spec/datetime/holidays_spec.py
- spec/profiles/gaps_spec.py
- If there is +/- 1kWh don't adjust the profile
>  procediment 10.12 del BOE de curves (pàgina 47712) de validació de mesures esmenta aquest marge que s'ha de tindre en compte.
> Don't adjust if is a margin of 1kWh

- enerdata/profiles/profile.py
- spec/profiles/gaps_spec.py
With this we can customize the difference for adjusting or not.
Eg.:
```python
profile = p.adjust(Tariff, {'P1': 320}, 1)
```
:warning:  By default difference is `0`
> Make adjust() accept difference

- enerdata/profiles/profile.py
instead of use make with values to avoid problems with the lack of OrderedDict in python 2.6
> Use _replace and unpack the dictionary to adjust profile measure

- enerdata/profiles/profile.py
Adjusting was not done by period but per total consumption. Following point 4.6 from procedure 10.12 must be done by period and +/-1kWh comparison must also be done by period.
There is also a problem when adjusting but i do not exactly know how to do it. When a period must be adjusted all the hours must be marked as ```kind_fact = 3```. By now it is done comparing if the original value is equal to the adjusted one, and this is not correct. Enerdata should mark someway the adjusted hours, so the erp knows it has been adjusted, independent from the value obtained when adjusting.
> FIX Adjust per period

- enerdata/contracts/tariff.py
- spec/contracts/tariff_spec.py
Fixed a bug where tariff would say that some normalized powers are not normalized due to wrong rounding.
> Fix: Tariff wouldn't accept some normalized powers

- enerdata/profiles/profile.py
- spec/profiles/gaps_spec.py
- spec/profiles/integration_spec.py
- spec/profiles/profile_spec.py
It improves the ProfileHour to store the `accumulated` energy to be used for the next hour.
Will be usefull at re-profiling / re-filling for partial points to be sure to correlate the pending amount of energy rounded on previous hour.
It updates the specs where a ProfileHour is used, and provide own specs to be sure that new property `accumulated` exists and at least one of them for a full month estimation is different than zero (statistically assertion).
Fix #84 Extend ProfileHour with next measure to accumulate
> ProfileHour with accumulated drag

- enerdata/profiles/profile.py
- spec/profiles/gaps_spec.py
- spec/profiles/integration_spec.py
- spec/profiles/profile_spec.py
This provides a mechanism to be able to define an initial accumulated energy for a Profile.
It's handled passing a new argument at `Profile` initialitzation called `accumulated`, accomplishing:
- be a float or a Decimal instance
- -1> accumulated < 1
This accumulated is loaded for the period of the first gap of this Profile.
To clarify with @ecarreras  if a period-based accumulate must be handled, just to apply the accumulated for the defined period, instead of the period of the first hour.
Tests are provided to validate it
Fix #86 Pass possible initial accumulated at Profile init
> Profile initialization with an initial accumulated energy

- enerdata/profiles/profile.py
- spec/profiles/gaps_spec.py
- spec/profiles/integration_spec.py
- spec/profiles/profile_spec.py
Related to #87, it seems like drag key used to handle the Dragging of the decimal part of current hour estimation points to the period of the past hour instead of the current one.
Maybe i'm not understanding properly the rounding process and simply it's not a bug, but I think that will be interesting to be analyzed with the team.
> Fix bug with drag key init at Profile.estimate

- enerdata/profiles/profile.py
Related to #87, it seems like drag key used to handle the Dragging of the decimal part of current hour estimation points to the period of the past hour instead of the current one.
Maybe i'm not understanding properly the rounding process and simply it's not a bug, but I think that will be interesting to be analyzed with the team.
```
(0, 'P2', datetime.datetime(2017, 9, 1, 0, 0, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>), ProfileHour(date=datetime.datetime(2017, 9, 1, 0, 0, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>), measure=1, valid=True, accumulated=Decimal('-0.139893554446')))
(1, 'P2', datetime.datetime(2017, 9, 1, 1, 0, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>), ProfileHour(date=datetime.datetime(2017, 9, 1, 1, 0, tzinfo=<DstTzInfo 'Europe/Madrid' …
```
> Fix BUG assigning drag period key

- enerdata/profiles/profile.py
- spec/profiles/profile_spec.py
Dragging method is now eligible at Profile initialization using the flag property `drag_by_period`.
If True, the dragging method is based on the period, if not, it will drag to the next gap.
Default drag method (if not provided) is based on perdiod to keep compatibility with existing enerdata.Profile usages.
Fix #101  Profile class must handle dragging method
> Profile with eligible dragging method

- enerdata/contracts/tariff.py
- spec/contracts/tariff_spec.py
The tariff 3.0A has a new restriction: all powers must be above the min power.
This PR adds this validation to the method `evaluate_powers`.
Tariff powers:
https://rfc.gisce.net/t/codigos-de-agregaciones/423
Close https://github.com/gisce/enerdata/issues/104
> Validate minpower in 3.0A

- enerdata/profiles/profile.py
- spec/coefficients/coefficients_spec.py
Get only the coefficients of the full months.
The file PERF_YYYYMM.txt carries all the days and hours included as follows:
```
2018;05;31;22;1;0.000136069486;0.000111580212;0.000111439358;0.000124703211;
2018;05;31;23;1;0.000125455061;0.000146546331;0.000103533335;0.000213501071;
2018;05;31;24;1;0.000101257604;0.000143837286;0.000092411636;0.000189206101;
```
So, when you want coefficients up to date x: 00h, you have to pass in 24h format
Example:
start_date = 2018-02-01 01:00
end_date = 2018-04-01 00:00
Will try to find coefficients of the month 04 !!! In the file PERF_201803 you have the hour 24.
Good way :heavy_check_mark:
```Python
di = datetime.datetime(2018, 4, 1, 1, 0)
df = datetime.datetime(2018, 6, 1, 0, 0)
get_coeffs(di, df)
>>>
Downloading coefficients for 4/2018
Downloading …
```
> Go back one day to download coefficients

- enerdata/profiles/profile.py
- spec/coefficients/coefficients_spec.py
Found out that modifying the dates as we did to get the REE coefficients didn't work properly for the coefficients received from ESIOS.
With this PR we make sure we only modify the dates if we are working with the REE class.
> Modify the coefficients dates only when profiling with REEProfile class

- enerdata/profiles/profile.py
www.ree.es has permanently moved its coefficient collection link
When you try to do `HTTPConnection()` a `www.ree.es`, it returns: **301 error code**
```Python
>>> conn = httplib.HTTPConnection(HOST)
>>> conn.reques('GET', '/sites/default/files/simel/perff/PERFF_201709.gz')
>>> r.status
301
``` 
Solving...
```Python
>>> conn = httplib.HTTPSConnection(HOST)
>>> conn.reques('GET', '/sites/default/files/simel/perff/PERFF_201709.gz')
>>> r.status
200
```
> Obtain profile coefficients using HTTPS

- enerdata/contracts/normalized_power.py
- spec/contracts/normalized_power_spec.py
- spec/contracts/tariff_spec.py
Since RD 15/2018 https://www.boe.es/boe/dias/2018/10/06/pdfs/BOE-A-2018-13593.pdf, 2.0 and 2.1  Normalized Powers includes multiples of 100 W until 15000 W. 
This modifies `NormalizedPower` class:
* `get_vol_int`: returns `(None, None)` when is 100 W multiple and not an old NormalizedPower
* `is_normalized`: includes 100 W multiples
* `get_norm_powers`: includes 100 W multiples on returned list
> New normalized 100 W multiples power

- enerdata/contracts/tariff.py
Can profile 3.1A LB with 3 periods
Can be done:
```Python
tariff = get_tariff_by_code('3.1A C2')(kva=kva)
```
> 3.1A LB 3 periods

- enerdata/profiles/profile.py
- spec/profiles/profile_spec.py
- The calculation of energy in self-consumption cannot give errors of division by zero.
- If a coefficient is zero, it will be assumed that no energy is generated (gap_energy = 0).
> Fixed ZeroDivisionError error when having sun coefficients at zero

- enerdata/profiles/profile.py
- spec/profiles/profile_spec.py
- The profiling must be carried out correctly in cases where there is energy in the P4.
- If there is energy in P4, it is added to P1 so that it is profiled correctly.
Closes #121
> Added a treatment for 31A6P tariffs when there is energy in P4 period

- enerdata/profiles/profile.py
Fix typo: `Setiembre` -> `Septiembre`
That produced an error when going to get for the coefficients of this concret month, because the official coefficient file is written like this.
> Fix typo on RE

- enerdata/datetime/solar_hour.py
- enerdata/profiles/profile.py
- spec/datetime/solar_hour_spec.py
- spec/datetime/station_spec.py
From #117 
Closes #117 
In RE profiling, the coefficients are indicated in solar hours, they must be translated at civil hours according to:
Los valores de las horas que aparecen en las tablas siguientes corresponden al tiempo solar. En el horario de invierno la hora civil corresponde a la hora solar más 1 unidad, y en el horario de verano la hora civil corresponde a la hora solar más 2 unidades. Los cambios de horario de invierno a verano o viceversa coincidirán con la fecha de cambio oficial de hora.
Is the first hour of the month corresponding to the last solar hour of the previous month?
> It is not a problem since the initial and final hours of the day of each month of each climatic zone are without sun, so coefficient = 0
> Translate civil hour to solar hour in RE

- requirements.txt
Limitar rquerimiento de la libreria workalendar para mantener compatibilidad con python 2.7
workalendar<8.0.0
> workalendar<8.0.0

- setup.py
Mantain python 2.7 compat limiting workalendar version on installation script
workalendar vesion <8.0.0
> Limitar version workalendar en el script de instalacion tambien

- requirements.txt
Fix pandas to v0.23.4 version to avoid a newer not compatible API
> Fix pandas to v0.23.4 version

- setup.py
If installed version via `pip install enerdata`, data csv are not included in the package
> Fix include csv files in packages setup

- requirements-dev.txt
Fix testing removed `py2` support by `mamba` on: https://github.com/nestorsalceda/mamba/releases/tag/v0.11.0
> Fix mamba testing py2 support

- enerdata/__init__.py
- enerdata/contracts/tariff.py
- enerdata/profiles/profile.py
- setup.py
- spec/profiles/profile_spec.py
Fix draft existent curve with applying losses.
Cases:
- Real and complete curve
- Curve with gaps
- Inexistent curve (estimate)
- Refix curve cannot duplicate the consumption losses
Todo:
Usabillity code integration:
- The fixit will also be used
- To apply losses, the rate must be instantiated as:`T31ALB(kva)`
- To apply losses on `estimate` method, just type: `tariff.apply_curve_losses(curve)`
> Fix curve with losses

- enerdata/contracts/tariff.py
- requirements.txt
- spec/contracts/tariff_spec.py
Se añade la funcion `def evaluate_powers_all_checks`, similar a `def evaluate_powers` con la diferencia que esta devuelve un listado de los errores (comprueva todas las validaciones)
> Añadir funcion para evaluar todas las validaciones de tarifa y acomular errores en el retorno

- enerdata/contracts/tariff.py
- enerdata/profiles/profile.py
- Se ha creado la tarifa `T1P` para usarla como perfilador universal de PVPC.
- Se ha corregido la obtención de perfiles para las tarifas TD.
> Perfilador universal de 1 período de energía y correcciones en la obtención de perfiles para PVPC

- enerdata/profiles/profile.py
Els perfils de REE a partir del 06/2021 només informent els coeficients nous, ja no informen els A, B, C i D.
> Fix format new profiles REE

- enerdata/profiles/profile.py
- spec/profiles/profile_spec.py
- Se ha corregido el desfasamiento de una hora entre los periodos y los perfiles de consumo para las tarifas de acceso TD.
- Se han implementado dos `tests` para garantizar el correcto funcionamiento de la perfilación de tarifas `2.0TD` y `3.0TD`.
- Se ha mejorado la casuística para obtener los coeficientes nuevos de perfilación para fechas iguales o posteriores al 1 de junio de 2021.
:warning: Esta última solución es temporal. Cuando REE publique los perfiles para 2022 habrá que estudiar el formato para adaptar los cambios.
> Correcciones en la perfilación de REE

- enerdata/profiles/profile.py
- spec/profiles/gaps_spec.py
- spec/profiles/integration_spec.py
- spec/profiles/profile_spec.py
- Se ha corregido el desfase temporal entre REE y ESIOS (1 hora).
- Se ha restado un minuto a todas las llamadas a la función que devuelve el período horario dadas una tarifa, una fecha y una hora.
> Corrección reparto periodos por horas en estimación y ajuste de curvas

- enerdata/contracts/tariff.py
- Las tarifas `6.1TD` y `6.1TDVE` se deben poder perfilar usando los coeficientes de perfilación de las tarifas `3.0TD` y `3.0TDVE`, respectivamente.
> Añadir coeficiente de perfilación a las tarifas 6.1TD y 6.1TDVE

- enerdata/contracts/tariff.py
- Ahora la función que obtiene el periodo de una tarifa en función de la fecha y la hora tiene en cuenta los días festivos, aunque estos no se hayan pasado por parámetro.
> Correcciones en la función que obtiene el periodo de una tarifa según la fecha

- enerdata/contracts/tariff.py
- Si se pasa un listado vacío (`[]`) como días festivos al obtener el periodo horario de una tarifa dada una fecha y una hora, la librería obtiene los días festivos que apliquen a dicha fecha y hora automáticamente en lugar de no usar días festivos.
> Se ha protegido el listado de días festivos al obtener el periodo horario para una tarifa y una fecha/hora

- enerdata/profiles/profile.py
- spec/coefficients/coefficients_spec.py
- Dado que el sitio web de `REE` no es infalible para descargar los coeficientes de perfilación, se ha creado un repositorio público en GitHub para almacenar los mismos a medida que lleguen mediante Concentrador Secundario.
- Se ha implementado un reintento a la hora de obtener los coeficientes de perfilación usando el repositorio público antes mencionado.
https://github.com/gisce/ree_montly_profiles
> Nuevo repositorio auxiliar de ficheros de coeficientes de perfiles de REE

- enerdata/profiles/profile.py
- Corregir el nombre del repositorio auxiliar de coeficientes de perfilación, para poder consultarlo debidamente si los coeficientes desaparecen de `ESIOS` temporalmente.
- Requiere https://github.com/gisce/ree_monthly_profiles/pull/1
> Correcciones en el acceso al repositorio auxiliar de coeficientes de perfilación

- enerdata/profiles/__init__.py
- enerdata/profiles/profile.py
- spec/profiles/profile_spec.py
- Al estimar la energia faltante (Wh) de una hora de una curva, si la energia estimada contenía decimales se guarda lo sobranet tras un redondeo con arrastre. El problema es que no se calcula bien el periodo donde se tenian que guardar el arrastre.
- Se ha fijado que el arrastre (dragger) tenga en cuenta máximo 10 decimales, para evitar discrepancias entre Python 2.7 y Python 3.11.
- Ahora ya se calcula bien el periodo.
- Cálculos revisados simulando la perfilación de consumo ara 4 días de septiembre de 2022 con una tarifa 2.0TD.
[exemple_perfilacio.xlsx](https://github.com/gisce/enerdata/files/13367519/exemple_perfilacio.xlsx)
- Coeficientes de perfilación definitivos para septiembre de 2022.
[PERFF_202209.gz](https://github.com/gisce/enerdata/files/13353657/PERFF_202209.gz)
> FIX Se añadia energia sobrante en periodo incorrecto al estimar
